"use strict";

const DEFINE_TYPE = {};
DEFINE_TYPE.NUMBER = 'NUMBER';
DEFINE_TYPE.INT = 'INT';
DEFINE_TYPE.UINT = 'UINT';
DEFINE_TYPE.STRING = 'STRING';
DEFINE_TYPE.BOOLEAN = 'BOOLEAN';
DEFINE_TYPE.FUNCTION = 'FUNCTION';
DEFINE_TYPE.ARRAY = 'ARRAY';
DEFINE_TYPE.OBJECT = 'OBJECT';

export default DEFINE_TYPE;